# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    files.mk                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wbraeckm <wbraeckm@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/25 16:38:11 by wbraeckm          #+#    #+#              #
#    Updated: 2020/02/05 13:51:31 by wbraeckm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

HEADERS = includes/builtin.h \
includes/lexer.h \
includes/prompt.h \
includes/sh.h

SRCSUBS = ./srcs \
./srcs/alias \
./srcs/builtins \
./srcs/builtins/cd \
./srcs/builtins/fc \
./srcs/builtins/jobs \
./srcs/builtins/test \
./srcs/env \
./srcs/env/utils \
./srcs/exec \
./srcs/exec/utils \
./srcs/hash \
./srcs/history \
./srcs/jobs \
./srcs/jobs/utils \
./srcs/lexer \
./srcs/lexer/apply \
./srcs/lexer/tokens \
./srcs/lexer/tokens/utils \
./srcs/lexer/utils \
./srcs/prompt \
./srcs/prompt/char_handler \
./srcs/prompt/char_handler/specials \
./srcs/prompt/char_handler/specials/handle_arrows \
./srcs/prompt/char_handler/specials/search \
./srcs/prompt/complete_executables \
./srcs/prompt/complete_executables/select \
./srcs/prompt/utils \
./srcs/utils \
./srcs/utils/buffer \
./srcs/utils/substitute \
./srcs/utils/substitute/utils \
./srcs/var \

ITEMS = /alias/add_alias.c \
/alias/get_alias.c \
/alias/has_alias.c \
/alias/remove_alias.c \
/alias/repl_alias.c \
/builtins/alias.c \
/builtins/bg.c \
/builtins/builtin_init.c \
/builtins/cd/cd.c \
/builtins/cd/cd_switch.c \
/builtins/cd/cd_utils.c \
/builtins/echo.c \
/builtins/exit.c \
/builtins/export.c \
/builtins/false.c \
/builtins/fc/fc.c \
/builtins/fc/fc_handle_e.c \
/builtins/fc/fc_handle_l.c \
/builtins/fc/fc_handle_s.c \
/builtins/fc/fc_read_opt.c \
/builtins/fc/fc_utils.c \
/builtins/fg.c \
/builtins/hash.c \
/builtins/history.c \
/builtins/jobs/jobs.c \
/builtins/jobs/jobs_print.c \
/builtins/pwd.c \
/builtins/rehash.c \
/builtins/set.c \
/builtins/test/cmp_op.c \
/builtins/test/test.c \
/builtins/test/test_op.c \
/builtins/true.c \
/builtins/type.c \
/builtins/unalias.c \
/builtins/unset.c \
/builtins/unsetenv.c \
/env/add_env.c \
/env/copy_env.c \
/env/count_env.c \
/env/get_env.c \
/env/get_env_clone.c \
/env/has_env.c \
/env/make_env_array.c \
/env/remove_env.c \
/env/repl_env.c \
/env/utils/path_change.c \
/exec/exec_cmd.c \
/exec/exec_proc.c \
/exec/exec_tree.c \
/exec/utils/cmd_is_empty.c \
/exec/utils/cmd_make_string.c \
/exec/utils/cmd_new.c \
/exec/utils/conditions.c \
/exec/utils/free_cmd.c \
/exec/utils/free_proc.c \
/exec/utils/free_tree.c \
/exec/utils/prepare_hdoc.c \
/exec/utils/prepare_proc.c \
/exec/utils/proc_apply_redir.c \
/exec/utils/proc_exec_cmd.c \
/exec/utils/proc_is_empty.c \
/exec/utils/proc_make_string.c \
/exec/utils/proc_new.c \
/exec/utils/redir_add_undo.c \
/exec/utils/redir_get_from.c \
/exec/utils/redir_open_file.c \
/exec/utils/redirections.c \
/exec/utils/syntax_error.c \
/hash/add_hash.c \
/hash/get_hash.c \
/hash/get_hash_ignorecase.c \
/hash/has_hash.c \
/hash/hash_add_use.c \
/hash/remove_hash.c \
/hash/reset_hash.c \
/history/add_history.c \
/history/get_history.c \
/history/init_history.c \
/history/query_history.c \
/history/remove_history.c \
/jobs/job_by_id.c \
/jobs/job_is_completed.c \
/jobs/job_is_stopped.c \
/jobs/job_notify.c \
/jobs/job_wait.c \
/jobs/jobs_add.c \
/jobs/jobs_continue.c \
/jobs/jobs_to_background.c \
/jobs/jobs_to_foreground.c \
/jobs/utils/jobs_last_status.c \
/lexer/apply/apply_ampersand.c \
/lexer/apply/apply_dampersand.c \
/lexer/apply/apply_dpipe.c \
/lexer/apply/apply_io_nb.c \
/lexer/apply/apply_newline.c \
/lexer/apply/apply_pipe.c \
/lexer/apply/apply_redir.c \
/lexer/apply/apply_word.c \
/lexer/build_tree.c \
/lexer/lexer.c \
/lexer/process.c \
/lexer/tokenization.c \
/lexer/tokens/ampersand.c \
/lexer/tokens/double_ampersand.c \
/lexer/tokens/double_greater.c \
/lexer/tokens/double_lesser.c \
/lexer/tokens/double_pipe.c \
/lexer/tokens/greater.c \
/lexer/tokens/greaterand.c \
/lexer/tokens/io_number.c \
/lexer/tokens/lesser.c \
/lexer/tokens/lesserand.c \
/lexer/tokens/new_line.c \
/lexer/tokens/null.c \
/lexer/tokens/pipe.c \
/lexer/tokens/semicolon.c \
/lexer/tokens/utils/token_free.c \
/lexer/tokens/word.c \
/lexer/utils/delimit.c \
/lexer/utils/delimit_specials.c \
/lexer/utils/delimit_utils.c \
/lexer/utils/lexer_free.c \
/lexer/utils/lexer_handle_alias.c \
/lexer/utils/make_stack_prompt.c \
/lexer/utils/stack.c \
/prompt/char_handler/char_dispatcher.c \
/prompt/char_handler/default_char_handler.c \
/prompt/char_handler/specials/edit/handle_copy.c \
/prompt/char_handler/specials/edit/handle_cut.c \
/prompt/char_handler/specials/edit/handle_edit.c \
/prompt/char_handler/specials/edit/handle_move.c \
/prompt/char_handler/specials/edit/handle_paste.c \
/prompt/char_handler/specials/handle_arrows/handle_arrows.c \
/prompt/char_handler/specials/handle_arrows/handle_arrows_select.c \
/prompt/char_handler/specials/handle_arrows/handle_shift_arrows.c \
/prompt/char_handler/specials/handle_arrows/next_line.c \
/prompt/char_handler/specials/handle_backspace.c \
/prompt/char_handler/specials/handle_empty.c \
/prompt/char_handler/specials/handle_escape.c \
/prompt/char_handler/specials/handle_ignore.c \
/prompt/char_handler/specials/handle_newline.c \
/prompt/char_handler/specials/handle_tab.c \
/prompt/char_handler/specials/search/handle_backspace_search.c \
/prompt/char_handler/specials/search/handle_char_search.c \
/prompt/char_handler/specials/search/handle_search.c \
/prompt/char_handler/specials/search/search_render.c \
/prompt/complete_executables/autocomplete_command.c \
/prompt/complete_executables/autocomplete_tools.c \
/prompt/complete_executables/complete_command.c \
/prompt/complete_executables/select/display.c \
/prompt/complete_executables/select/display_scroll.c \
/prompt/complete_executables/select/get_info.c \
/prompt/complete_executables/select/render.c \
/prompt/complete_executables/select/select.c \
/prompt/prompt.c \
/prompt/utils/calc_cursor_pos.c \
/prompt/utils/cursor_movement.c \
/prompt/utils/free_prompt.c \
/prompt/utils/gen_prompt.c \
/prompt/utils/print.c \
/prompt/utils/reprint.c \
/prompt/utils/transform_pos.c \
/prompt/utils/wcharlen.c \
/sh.c \
/utils/buffer/buff_init.c \
/utils/buffer/buff_insert.c \
/utils/buffer/buff_remove.c \
/utils/free_sh.c \
/utils/gen_prompt_string.c \
/utils/get_cursor_pos.c \
/utils/get_git_branch.c \
/utils/get_hostname.c \
/utils/get_signal_str.c \
/utils/getpwd.c \
/utils/gettermsize.c \
/utils/init_aliases.c \
/utils/init_interactive_mode.c \
/utils/init_internal_vars.c \
/utils/is_builtin.c \
/utils/is_char_escaped.c \
/utils/is_dir.c \
/utils/is_fifo.c \
/utils/random.c \
/utils/resolve_path.c \
/utils/ring_bell.c \
/utils/signal_handlers.c \
/utils/str_is_name.c \
/utils/strlen_nocolor.c \
/utils/substitute/substitute.c \
/utils/substitute/substitute_cmd.c \
/utils/substitute/substitute_event.c \
/utils/substitute/substitute_param.c \
/utils/substitute/substitute_parambrace.c \
/utils/substitute/substitute_spec_event.c \
/utils/substitute/substitute_specials.c \
/utils/substitute/substitute_tilde.c \
/utils/substitute/utils/apply_bparam_operator.c \
/utils/substitute/utils/apply_bparam_operator2.c \
/utils/substitute/utils/bparam_operator.c \
/utils/substitute/utils/free_bparam.c \
/utils/substitute/utils/free_subst.c \
/var/add_var.c \
/var/clone_var.c \
/var/get_exit_code.c \
/var/get_var.c \
/var/get_var_clone.c \
/var/has_var.c \
/var/remove_var.c \
/var/repl_var.c \
/var/set_exit_code.c \
/var/var_del_filter.c
