# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    files.mk                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wbraeckm <wbraeckm@student.s19.be>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/25 16:38:11 by wbraeckm          #+#    #+#              #
#    Updated: 2020/02/05 14:03:06 by wbraeckm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIBFT_HEADERS = $(LIBFT_INCLUDES)/ft_printf.h \
$(LIBFT_INCLUDES)/get_next_line.h \
$(LIBFT_INCLUDES)/libft.h \
$(LIBFT_INCLUDES)/libft_char.h \
$(LIBFT_INCLUDES)/libft_int.h \
$(LIBFT_INCLUDES)/libft_lst.h \
$(LIBFT_INCLUDES)/libft_map.h \
$(LIBFT_INCLUDES)/libft_math.h \
$(LIBFT_INCLUDES)/libft_mem.h \
$(LIBFT_INCLUDES)/libft_opt.h \
$(LIBFT_INCLUDES)/libft_put.h \
$(LIBFT_INCLUDES)/libft_stdarg.h \
$(LIBFT_INCLUDES)/libft_str.h \
$(LIBFT_INCLUDES)/libft_tree.h \
$(LIBFT_INCLUDES)/libft_types.h \
$(LIBFT_INCLUDES)/libft_vec.h \
$(LIBFT_INCLUDES)/libft_vlq.h \
$(LIBFT_INCLUDES)/libft_wstr.h

LIBFT_SRCSUBS = $(LIBFT_FOLDER)srcs \
$(LIBFT_FOLDER)srcs/char \
$(LIBFT_FOLDER)srcs/gnl \
$(LIBFT_FOLDER)srcs/int \
$(LIBFT_FOLDER)srcs/lst \
$(LIBFT_FOLDER)srcs/map \
$(LIBFT_FOLDER)srcs/math \
$(LIBFT_FOLDER)srcs/mem \
$(LIBFT_FOLDER)srcs/opt \
$(LIBFT_FOLDER)srcs/printf \
$(LIBFT_FOLDER)srcs/printf/colors \
$(LIBFT_FOLDER)srcs/printf/handlers \
$(LIBFT_FOLDER)srcs/printf/parser \
$(LIBFT_FOLDER)srcs/put \
$(LIBFT_FOLDER)srcs/stdarg \
$(LIBFT_FOLDER)srcs/str \
$(LIBFT_FOLDER)srcs/tree \
$(LIBFT_FOLDER)srcs/vec \
$(LIBFT_FOLDER)srcs/vlq \
$(LIBFT_FOLDER)srcs/wstr

LIBFT_ITEMS = /char/ft_isalnum.c \
/char/ft_isalpha.c \
/char/ft_isascii.c \
/char/ft_isdigit.c \
/char/ft_islower.c \
/char/ft_isprint.c \
/char/ft_isupper.c \
/char/ft_itoc.c \
/char/ft_itoc_base.c \
/char/ft_swapchar.c \
/char/ft_tolower.c \
/char/ft_toupper.c \
/gnl/ft_clear_gnl.c \
/gnl/get_next_line.c \
/int/ft_abs.c \
/int/ft_atoi.c \
/int/ft_atol.c \
/int/ft_intcmp.c \
/int/ft_intlen.c \
/int/ft_intlen_base.c \
/int/ft_intmax.c \
/int/ft_intmin.c \
/int/ft_intsort.c \
/int/ft_itoa.c \
/int/ft_itoa_base.c \
/int/ft_max.c \
/int/ft_min.c \
/int/ft_range.c \
/int/ft_swapint.c \
/int/ft_swaplong.c \
/int/ft_swapshort.c \
/int/ft_uintlen.c \
/int/ft_uintlen_base.c \
/int/ft_uitoa.c \
/int/ft_uitoa_base.c \
/lst/ft_lstadd.c \
/lst/ft_lstdel.c \
/lst/ft_lstdelone.c \
/lst/ft_lstiter.c \
/lst/ft_lstlast.c \
/lst/ft_lstlen.c \
/lst/ft_lstmap.c \
/lst/ft_lstnew.c \
/lst/ft_lstpop.c \
/lst/ft_lstpushback.c \
/lst/ft_lstpushfront.c \
/lst/ft_lstremoveif.c \
/lst/ft_lstsortinsert.c \
/lst/ft_lsttoarray.c \
/map/ft_mapclear.c \
/map/ft_mapclone.c \
/map/ft_mapcontains.c \
/map/ft_mapdel.c \
/map/ft_mapfilter.c \
/map/ft_mapget.c \
/map/ft_mapgetordef.c \
/map/ft_maphash.c \
/map/ft_mapisempty.c \
/map/ft_mapmaxsize.c \
/map/ft_mapnew.c \
/map/ft_mapprint.c \
/map/ft_mapput.c \
/map/ft_mapputnoclone.c \
/map/ft_maprehash.c \
/map/ft_mapremove.c \
/map/ft_mapreplace.c \
/map/ft_mapsize.c \
/math/ft_ilerp.c \
/math/ft_lerp.c \
/math/ft_pow.c \
/mem/ft_bzero.c \
/mem/ft_calloc.c \
/mem/ft_memalloc.c \
/mem/ft_memccpy.c \
/mem/ft_memchr.c \
/mem/ft_memcmp.c \
/mem/ft_memcpy.c \
/mem/ft_memdel.c \
/mem/ft_memdup.c \
/mem/ft_memmove.c \
/mem/ft_memset.c \
/mem/ft_memswap.c \
/mem/ft_ptrsort.c \
/mem/ft_realloc.c \
/opt/ft_getopt.c \
/printf/colors/ft_colors.c \
/printf/ft_dprintf.c \
/printf/ft_printf.c \
/printf/ft_printf_fd.c \
/printf/ft_printf_put.c \
/printf/handlers/ft_convert.c \
/printf/handlers/ft_handler.c \
/printf/handlers/ft_handler_binary.c \
/printf/handlers/ft_handler_char.c \
/printf/handlers/ft_handler_float.c \
/printf/handlers/ft_handler_hexa.c \
/printf/handlers/ft_handler_int.c \
/printf/handlers/ft_handler_none.c \
/printf/handlers/ft_handler_octal.c \
/printf/handlers/ft_handler_pointer.c \
/printf/handlers/ft_handler_printed.c \
/printf/handlers/ft_handler_string.c \
/printf/handlers/ft_handler_tab.c \
/printf/handlers/ft_handler_unsigned.c \
/printf/parser/ft_printf_parser.c \
/printf/parser/ft_printf_parser_helper.c \
/put/ft_putchar.c \
/put/ft_putchar_fd.c \
/put/ft_putendl.c \
/put/ft_putendl_fd.c \
/put/ft_putnbr.c \
/put/ft_putnbr_fd.c \
/put/ft_putnchar.c \
/put/ft_putnchar_fd.c \
/put/ft_putnonprint.c \
/put/ft_putnonprint_fd.c \
/put/ft_putnstr.c \
/put/ft_putnstr_fd.c \
/put/ft_putstr.c \
/put/ft_putstr_fd.c \
/put/ft_puttab.c \
/put/ft_puttab_fd.c \
/put/ft_puttab_join.c \
/put/ft_puttab_join_fd.c \
/stdarg/ft_arg_at.c \
/str/ft_freesplit.c \
/str/ft_splitlen.c \
/str/ft_strcat.c \
/str/ft_strchr.c \
/str/ft_strclr.c \
/str/ft_strcmp.c \
/str/ft_strcountchar.c \
/str/ft_strcpy.c \
/str/ft_strcspn.c \
/str/ft_strdel.c \
/str/ft_strdup.c \
/str/ft_strequ.c \
/str/ft_strequignorecase.c \
/str/ft_strfind.c \
/str/ft_strformat.c \
/str/ft_strhash.c \
/str/ft_strinsert.c \
/str/ft_strisalnum.c \
/str/ft_strisascii.c \
/str/ft_strisnumber.c \
/str/ft_striter.c \
/str/ft_striteri.c \
/str/ft_strjoin.c \
/str/ft_strlcat.c \
/str/ft_strlen.c \
/str/ft_strmap.c \
/str/ft_strmapi.c \
/str/ft_strncat.c \
/str/ft_strncmp.c \
/str/ft_strncpy.c \
/str/ft_strndel.c \
/str/ft_strndup.c \
/str/ft_strnequ.c \
/str/ft_strnew.c \
/str/ft_strnstr.c \
/str/ft_strrchr.c \
/str/ft_strrepl.c \
/str/ft_strrev.c \
/str/ft_strshift.c \
/str/ft_strsort.c \
/str/ft_strsplit.c \
/str/ft_strsplitcharset.c \
/str/ft_strsplitwhitespace.c \
/str/ft_strspn.c \
/str/ft_strsrepl.c \
/str/ft_strsreplall.c \
/str/ft_strstartswith.c \
/str/ft_strstartwith_ncs.c \
/str/ft_strstr.c \
/str/ft_strsub.c \
/str/ft_strtok.c \
/str/ft_strtok_r.c \
/str/ft_strtolower.c \
/str/ft_strtoupper.c \
/str/ft_strtrijoin.c \
/str/ft_strtrim.c \
/str/ft_tabjoin.c \
/tree/ft_treeinsert.c \
/tree/ft_treeiter_infix.c \
/tree/ft_treeiter_prefix.c \
/tree/ft_treeiter_suffix.c \
/tree/ft_treenew.c \
/tree/ft_treenewcpy.c \
/vec/ft_veccpush.c \
/vec/ft_vecdel.c \
/vec/ft_vecdestroy.c \
/vec/ft_vecfree.c \
/vec/ft_vecget.c \
/vec/ft_vecgettop.c \
/vec/ft_vecinit.c \
/vec/ft_veciter.c \
/vec/ft_veciteri.c \
/vec/ft_vecmaxsize.c \
/vec/ft_vecnpush.c \
/vec/ft_vecpop.c \
/vec/ft_vecpush.c \
/vec/ft_vecput.c \
/vec/ft_vecresize.c \
/vec/ft_vecset.c \
/vec/ft_vecsize.c \
/vec/ft_vecsort.c \
/vlq/ft_binstrtovlq.c \
/vlq/ft_vlq_count_actbits.c \
/vlq/ft_vlq_count_sigbit.c \
/vlq/ft_vlqadd.c \
/vlq/ft_vlqadd_set.c \
/vlq/ft_vlqcmp.c \
/vlq/ft_vlqdel.c \
/vlq/ft_vlqdup.c \
/vlq/ft_vlqlen.c \
/vlq/ft_vlqmul.c \
/vlq/ft_vlqnew.c \
/vlq/ft_vlqof.c \
/vlq/ft_vlqtrim.c \
/wstr/ft_wstrfromindex.c \
/wstr/ft_wstrindex.c \
/wstr/ft_wstrlen.c \
/wstr/ft_wstrsub.c
